---
- name: Get Role
  k8s_info:
    api_version: rbac.authorization.k8s.io/v1
    kind: Role
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
  register: ocp_role

- name: Set Application Domain
  set_fact:
    ocp_role: "{{ ocp_role | json_query('resources[*].rules[*].verbs') }}"
